apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
      metadata:
        name: flask-app
        labels:
          app: flask-app
      spec:
        containers:
        - name: flask-container
          image: naimat1233/flask-app
          ports:
          - containerPort: 5000
