pipeline { 
    agent any
    environment { 
        DOCKER_IMAGE = 'naimat1233/flask-app:latest'
        CONTAINER_NAME = 'myapp_container'
    }
    stages {
        stage('Clone') {
            steps { 
                git branch: 'main', url: 'https://github.com/Naimat250/DevOpsProjects.git'
                echo 'Clone Successfully'
            }
        }
        stage('Docker Compose Down and Up') {
            steps { 
                dir('Multistage-Flask-App') {
                    // Bring down any existing containers
                    sh 'docker-compose down'
                    echo 'Docker Compose Down Successfully'
                    
                    // Build and run services using Docker Compose
                    sh 'docker-compose up -d --build'
                    echo 'Docker Compose Up Successfully'
                }
            }
        }
        stage('Push to Docker Hub') {
            steps { 
                withCredentials([usernamePassword(credentialsId: "DockerHubCreds", passwordVariable: "dockerPass", usernameVariable: "dockerUser")]) { 
                    sh "docker login -u ${env.dockerUser} -p ${env.dockerPass}" 
                    sh "docker tag naimat1233/flask-app:latest ${env.dockerUser}/flask-app:latest"
                    sh "docker push ${env.dockerUser}/flask-app:latest"
                    echo 'Pushed to Docker Hub successfully'
                }
            }
        }
    }
   
}
